name: web_view_ble
description: Add Bluetooth Low Energy Support in WebView Flutter
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_inappwebview: ^5.4.3+7
  quick_blue: ^0.5.0-dev.2
# flutter_reactive_ble: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/stringview.js
    - assets/WBUtils.js
    - assets/WBEventTarget.js
    - assets/WBBluetoothUUID.js
    - assets/WBDevice.js
    - assets/WBBluetoothRemoteGATTServer.js
    - assets/WBBluetoothRemoteGATTService.js
    - assets/WBBluetoothRemoteGATTCharacteristic.js
    - assets/WBPolyfill.js
  plugin:
    platforms:
      android:
        package: com.example.web_view_ble
        pluginClass: WebViewBlePlugin
      ios:
        pluginClass: WebViewBlePlugin
